### ISSUE TITLE
smslib v3 in Linux x64 - RXTXCommDriver

### ISSUE THREAD

**Issue by anshu-s** [smslib/smslib-v3#19]
Hi

I am stuck in the x64 RXTX Exception. kindly advice. 
I have kept value of javax.comm.properties in /jre/lib/
Driver=gnu.io.RXTXCommDriver

Logs
java.io.IOException: Error instantiating class gnu.io.RXTXCommDriver 
gnu.io.RXTXCommDriver 
	at javax.comm.CommPortIdentifier.loadDriver(CommPortIdentifier.java:238)
	at javax.comm.CommPortIdentifier.<clinit>(CommPortIdentifier.java:109)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.smslib.helper.CommPortIdentifier.<clinit>(CommPortIdentifier.java:66)
	at org.smslib.modem.SerialModemDriver.connectPort(SerialModemDriver.java:69)
	at org.smslib.modem.AModemDriver.connect(AModemDriver.java:114)
	at org.smslib.modem.ModemGateway.startGateway(ModemGateway.java:189)
	at org.smslib.Service$1Starter.run(Service.java:277)
Exception in thread "Thread-5" java.lang.UnsatisfiedLinkError: com.sun.comm.SunrayInfo.isSessionActive()Z
	at com.sun.comm.SunrayInfo.isSessionActive(Native Method)
	at com.sun.comm.Portmapping.registerCommPorts(Portmapping.java:155)
	at com.sun.comm.Portmapping.refreshPortDatabase(Portmapping.java:100)
	at javax.comm.CommPortIdentifier.<clinit>(CommPortIdentifier.java:138)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.smslib.helper.CommPortIdentifier.<clinit>(CommPortIdentifier.java:66)
	at org.smslib.modem.SerialModemDriver.connectPort(SerialModemDriver.java:69)
	at org.smslib.modem.AModemDriver.connect(AModemDriver.java:114)
	at org.smslib.modem.ModemGateway.startGateway(ModemGateway.java:189)
	at org.smslib.Service$1Starter.run(Service.java:277)
15199  2016-01-06 18:58:35,651 [WatchDog] DEBUG org.smslib.threading.AServiceThread  - Running...
^C28031  2016-01-06 18:58:48,483 [Thread-0] INFO  org.smslib.smsserver.SMSServer$Shutdown  - SMSServer shutting down, please wait...
28032  2016-01-06 18:58:48,484 [Thread-0] INFO  org.smslib.smsserver.interfaces.Interface

**Comment by anshu-s** [comment]
I taken ref from http://rxtx.qbang.org/wiki/index.php/Installation_on_Linux 
and tried apt-get install librxtx-java but still same :( 


199    2016-01-06 19:35:20,485 [WatchDog] DEBUG org.smslib.threading.AServiceThread  - Running...
202    2016-01-06 19:35:20,488 [Thread-5] INFO  org.smslib.modem.SerialModemDriver  - GTW: modem1: Opening: /dev/ttyACM8 @115200
202    2016-01-06 19:35:20,488 [DelayQueueManager] DEBUG org.smslib.queues.AbstractQueueManager$DelayQueueManager  - DelayQueueManager running...

java.io.IOException: Error instantiating class gnu.io.RXTXCommDriver 
gnu.io.RXTXCommDriver 
	at javax.comm.CommPortIdentifier.loadDriver(CommPortIdentifier.java:238)
	at javax.comm.CommPortIdentifier.<clinit>(CommPortIdentifier.java:109)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.smslib.helper.CommPortIdentifier.<clinit>(CommPortIdentifier.java:66)
	at org.smslib.modem.SerialModemDriver.connectPort(SerialModemDriver.java:69)
	at org.smslib.modem.AModemDriver.connect(AModemDriver.java:114)
	at org.smslib.modem.ModemGateway.startGateway(ModemGateway.java:189)
	at org.smslib.Service$1Starter.run(Service.java:277)
Exception in thread "Thread-5" java.lang.UnsatisfiedLinkError: com.sun.comm.SunrayInfo.isSessionActive()Z
	at com.sun.comm.SunrayInfo.isSessionActive(Native Method)
	at com.sun.comm.Portmapping.registerCommPorts(Portmapping.java:155)
	at com.sun.comm.Portmapping.refreshPortDatabase(Portmapping.java:100)
	at javax.comm.CommPortIdentifier.<clinit>(CommPortIdentifier.java:138)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.smslib.helper.CommPortIdentifier.<clinit>(CommPortIdentifier.java:66)
	at org.smslib.modem.SerialModemDriver.connectPort(SerialModemDriver.java:69)
	at org.smslib.modem.AModemDriver.connect(AModemDriver.java:114)
	at org.smslib.modem.ModemGateway.startGateway(ModemGateway.java:189)
	at org.smslib.Service$1Starter.run(Service.java:277)
15202  2016-01-06 19:35:35,488 [WatchDog] DEBUG org.smslib.threading.AServiceThread  - Running...
30202  2016-01-06 19:35:50,488 [WatchDog] DEBUG org.smslib.threading.AServiceThread  - Running...
45203  2016-01-06 19:36:05,489 [WatchDog] DEBUG org.smslib.threading.AServiceThread  - Running...

**Comment by tdelenikas** [comment]
You don't need the `javax.comm.properties` when working with RxTx. You just need `jre/bin/rxtxSerial.dll` and `jre/lib/ext/RXTXcomm.jar`.

**Comment by anshu-s** [comment]
SO precisely If i am using RXTX i shall ignore using  javax.comm. Pl advise
